spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_db?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: YmIUGQw6KeJmIPnG??&xh!
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 910
ii:
  jwt:
    issuer: natsukashiiz.xyz
    expirationMs: 3600000
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem