mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:6033/blog_test?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
ii:
  jwt:
    issuer: natsukashiiz
    expirationMs: 31556952000
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem

server:
  port: 8080
logging:
  level:
    com.natsukashiiz.iiserverapi: DEBUG